name: "Poetry export requirements.txt file"
description: "Export requirements.txt file from poetry"
runs:
  using: composite
  steps:
    - run: python -m pip install poetry
      shell: bash
    - run: poetry export -f requirements.txt --without-hashes --output requirements.txt
      shell: bash
branding:
  icon: code
  color: blue
