name: "CI"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Sample pyproject.toml file
      run: |-
          cat > pyproject.toml << EOF
          [tool.poetry]
          name = "sampleenvfile"
          version = "1.0.0"
          description = ""
          authors = []

          [tool.poetry.dependencies]
          python = "^3.9"
          urllib3 = "^1.26"

          [build-system]
          requires = ["poetry-core>=1.0.0"]
          build-backend = "poetry.core.masonry.api"

          EOF
    - name: Test default
      uses: ./
    - name: Test without-hashes
      uses: ./
      with:
        without-hashes: false
    - name: Test outfile-name
      uses: ./
      with:
        outfile-name: requirements-new.txt
    - name: Show requirements.txt file
      run: |-
          cat requirements.txt
          cat requirements-new.txt
