name: "CI"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3

    - name: Sample pyproject.toml file
      run: |-
          cat > pyproject.toml << EOF
          [tool.poetry]
          name = "sampleenvfile"
          version = "1.0.0"
          description = ""
          authors = []

          [tool.poetry.dependencies]
          python = "^3.9"
          urllib3 = "^1.26"

          [build-system]
          requires = ["poetry-core>=1.0.0"]
          build-backend = "poetry.core.masonry.api"

          EOF
  
    - id: test-default
      name: Test default
      uses: ./

    - name: Check custom-file-name
      run: |-
        T_FILE_NAME=${{ steps.test-default.outputs.custom-file-name }}
        if [ -e $T_FILE_NAME ]
        then
            echo "file exists"
        else
            echo "file does not exists"
            exit 1
        fi

    - id: test-outfile-name
      name: Test outfile-name
      uses: ./
      with:
        without-hashes: false
        outfile-name: requirements-custom-name.txt

    - name: Check outfile-name
      run: |-
        T_FILE_NAME=${{ steps.test-outfile-name.outputs.custom-file-name }}
        if [ -e $T_FILE_NAME ]
        then
            echo "file exists"
        else
            echo "file does not exists"
            exit 1
        fi

    - id: test-without-hashes
      name: Test without-hashes
      uses: ./
      with:
        without-hashes: true
        outfile-name: requirements-without-hashes.txt

    - name: Check without-hashes
      run: |-
        T_FILE_NAME=${{ steps.test-without-hashes.outputs.custom-file-name }}
        if [ -e $T_FILE_NAME ]
        then
            echo "file exists"
        else
            echo "file does not exists"
            exit 1
        fi
